# Numpy Exercise

#### 1. Import the numpy package under the name as np  

In [1]:
import numpy as np

#### 2. Print the numpy version and the configuration 

In [2]:
print(np.__version__)
print(np.show_config())

1.20.3
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/rohit/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/rohit/anaconda3\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/rohit/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/rohit/anaconda3\\Library\\include']
lapack_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/rohit/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/rohit/anaconda3\\Library\\include']
lapack_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/rohit/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/rohit/anaconda3\\Library\\include']
None


#### 3. Create a null vector of size 10

In [8]:
arr=np.zeros(10)
print(arr)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4.  How to find the memory size of any array

In [9]:
a = arr.size
b = arr.itemsize
print("{} bytes".format(a*b))


80 bytes


#### 5.  How to get the documentation of the numpy add function from the command line? 

In [10]:
np.add?

#### 6.  Create a null vector of size 10 but the fifth value which is 1

In [11]:
arr1=np.zeros(10)
arr1[4]=1
print(arr1)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7.  Create a vector with values ranging from 10 to 49

In [13]:
arr2=np.arange(10,50,1)
print(arr2)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 8.  Reverse a vector (first element becomes last)

In [14]:
np.flipud(arr2)

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

#### 9.  Create a 3x3 matrix with values ranging from 0 to 8

In [16]:
x=np.random.randint(0,9,(3,3))
print(x)

[[0 5 8]
 [2 8 6]
 [8 4 2]]


#### 10. Find indices of non-zero elements from \[1,2,0,0,4,0\]

In [18]:
arr=np.array([1,2,0,0,4,0])
res=np.where(arr!=0)
res

(array([0, 1, 4], dtype=int64),)

#### 11. Create a 3x3 identity matrix

In [19]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 12. Create a 3x3x3 array with random values

In [21]:
np.random.random((3,3,3))

array([[[0.36901142, 0.13202628, 0.60645439],
        [0.15775078, 0.09084214, 0.04361696],
        [0.30881563, 0.77539023, 0.34942606]],

       [[0.70038489, 0.90101595, 0.86646346],
        [0.43861957, 0.91625817, 0.01397041],
        [0.06352355, 0.93911772, 0.18405949]],

       [[0.37322809, 0.55588992, 0.56041228],
        [0.16479367, 0.21731006, 0.0272401 ],
        [0.44337823, 0.02147531, 0.63028504]]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values

In [22]:
y=np.random.random((10,10))
a=np.min(y)
b=np.max(y)
print(a,b)

0.015474326926848025 0.9997629195149481


#### 14. Create a random vector of size 30 and find the mean value

In [24]:
arr=np.random.random(10)
ans=np.mean(arr)
ans

0.5811333001915185

#### 15. Create a 2d array with 1 on the border and 0 inside

In [25]:
ans = np.ones((5,5))
ans[1:-1,1:-1] = 0
ans

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

#### 16. How to add a border (filled with 0's) around an existing array?

In [26]:
ans = np.ones((3,3))
np.pad(ans,pad_width = 1, mode = 'constant',constant_values = 0)

array([[0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 0.],
       [0., 1., 1., 1., 0.],
       [0., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0.]])

#### 17. What is the result of the following expression?

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [27]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == (3 * 0.1))

nan
False
False
nan
True
False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [28]:
a = np.diag([1,2,3,4],-1)
a

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern

In [29]:
ans = np.zeros((8,8),dtype=int)
ans[1::2,::2] = 1
ans[::2,1::2] = 1
ans

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [30]:
np.unravel_index(99, (6,7,8))

(1, 5, 3)